# Generated by Django 5.2.9 on 2025-12-19 23:19

import books.utils.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=books.utils.paths.book_cover_upload_path),
        ),
    ]
